#ifndef AERC_SINK_PROBE_H
#define AERC_SINK_PROBE_H

#include "aerc_recovery_sink.h"

#define AERC_SINK_PROBE_HOLD_SCENARIO_ID  0x53374541u
#define AERC_SINK_PROBE_ENTER_SCENARIO_ID 0x53374542u
#define AERC_SINK_PROBE_BAD_SCENARIO_ID   0x5337454Fu

void AERC_SPROBE_Main(void);

#endif
