#!/usr/bin/env python3
"""Build the local short-form TAES Paper-2 candidate in isolated IEEEtran outputs.

This builder is for pagination/format QA only. It reads the untracked
TAES_10P_MANUSCRIPT_DRAFT.md generated by TAES_CREATE_10PAGE_CANDIDATE.py,
verifies its expected SHA-256, renders only the three short-main tables, and
writes TAES_10P_* development artifacts. It never overwrites TAES_MANUSCRIPT.pdf
or any frozen science/manuscript source.
"""

from __future__ import annotations

import re
from pathlib import Path

import TAES_BUILD_IEEETRAN as base

ROOT = Path(__file__).resolve().parent
SHORT_MD = ROOT / "TAES_10P_MANUSCRIPT_DRAFT.md"
OUT_TEX = ROOT / "TAES_10P_MANUSCRIPT_IEEETRAN_DEV.tex"
OUT_PDF = ROOT / "TAES_10P_MANUSCRIPT_IEEETRAN_DEV.pdf"
OUT_LOG = ROOT / "TAES_10P_MANUSCRIPT_IEEETRAN_DEV.log"
OUT_AUDIT = ROOT / "TAES_10P_IEEETRAN_BUILD_AUDIT.txt"

EXPECTED_SHORT_MD = "5926d116acc877859545bd5e0e2829132894de5298d7ff3e3cd6123b4665cbd1"

TABLE_CAPTIONS = {
    "I": "Selected Study-3 residual-boundary results",
    "II": "Selected Study-4 first/systematic thresholds",
    "III": "Study-6 residual incorrect states and benign assurance loss",
}

TABLE_SPECS = {
    "I": [
        r">{\raggedright\arraybackslash}p{2.65in}",
        r">{\centering\arraybackslash}p{1.75in}",
        r">{\centering\arraybackslash}p{1.55in}",
    ],
    "II": [
        r">{\raggedright\arraybackslash}p{1.00in}",
        r">{\centering\arraybackslash}p{2.65in}",
        r">{\centering\arraybackslash}p{2.65in}",
    ],
    "III": [
        r">{\raggedright\arraybackslash}p{1.55in}",
        r">{\raggedright\arraybackslash}p{3.25in}",
        r">{\centering\arraybackslash}p{0.70in}",
        r">{\centering\arraybackslash}p{0.85in}",
    ],
}

TABLE_HEADER_KEYS = {
    "Evidence / contact / policy": "I",
    "Rule": "II",
    "Gate": "III",
}


def verify_short_binding() -> None:
    if not SHORT_MD.is_file():
        raise SystemExit(
            "ERROR: short manuscript is missing. Run TAES_CREATE_10PAGE_CANDIDATE.py first."
        )
    actual = base.sha256(SHORT_MD)
    if actual != EXPECTED_SHORT_MD:
        raise SystemExit(
            "ERROR: short manuscript hash mismatch: "
            f"expected={EXPECTED_SHORT_MD} actual={actual}"
        )


def extract_short_tables(body_md: str) -> tuple[str, dict[str, str]]:
    lines = body_md.splitlines()
    out: list[str] = []
    tables_rendered: dict[str, str] = {}
    pending_caption: tuple[str, str] | None = None
    i = 0

    while i < len(lines):
        line = lines[i]
        cap_match = re.match(r"^\*\*Table\s+([IVX]+)\.\s+(.+?)\*\*$", line.strip())
        if cap_match:
            pending_caption = (cap_match.group(1), cap_match.group(2))
            i += 1
            while i < len(lines) and not lines[i].strip():
                i += 1
            continue

        if line.strip().startswith("|") and i + 1 < len(lines) and base.is_table_separator(lines[i + 1]):
            header = base.markdown_table_cells(line)
            j = i + 2
            rows: list[list[str]] = []
            while j < len(lines) and lines[j].strip().startswith("|"):
                rows.append(base.markdown_table_cells(lines[j]))
                j += 1

            roman = TABLE_HEADER_KEYS.get(header[0])
            if not roman:
                raise SystemExit(f"ERROR: unrecognized short-main table header: {header[0]}")
            if pending_caption and pending_caption[0] != roman:
                raise SystemExit(
                    f"ERROR: pending caption Table {pending_caption[0]} does not match Table {roman}"
                )
            if pending_caption:
                expected = TABLE_CAPTIONS[roman]
                if pending_caption[1] != expected:
                    raise SystemExit(
                        f"ERROR: Table {roman} caption mismatch: expected={expected!r} observed={pending_caption[1]!r}"
                    )
            pending_caption = None
            if roman in tables_rendered:
                raise SystemExit(f"ERROR: duplicate Table {roman}")

            tables_rendered[roman] = base.render_table(roman, header, rows)
            out.extend(["", f"TAES10PTABLE{roman}PLACEHOLDER", ""])
            i = j
            continue

        out.append(line)
        i += 1

    if pending_caption:
        raise SystemExit(f"ERROR: unmatched Table {pending_caption[0]} caption")
    if set(tables_rendered) != {"I", "II", "III"}:
        raise SystemExit(
            f"ERROR: expected short-main Tables I-III, parsed {sorted(tables_rendered)}"
        )
    return "\n".join(out), tables_rendered


def build_short_body_latex(body_md: str) -> str:
    stripped, tables = extract_short_tables(body_md)
    stripped = base.preprocess_headings(stripped)
    proc = base.run(
        [
            base.command_path("pandoc"),
            "--from=gfm",
            "--to=latex",
            "--wrap=none",
            "--top-level-division=section",
        ],
        input_text=stripped + "\n",
    )
    if proc.returncode != 0:
        raise SystemExit("ERROR: short-main pandoc conversion failed:\n" + proc.stdout)
    latex = proc.stdout
    for roman, rendered in tables.items():
        token = f"TAES10PTABLE{roman}PLACEHOLDER"
        if token not in latex:
            raise SystemExit(f"ERROR: Pandoc output lost Table {roman} placeholder")
        latex = latex.replace(token, rendered, 1)
    return latex.strip()


def convert_common_math(tex: str) -> tuple[str, int]:
    replacements = [
        (
            r"\texttt{Q\_j(E\_j) in \{0,1\}}",
            r"\[Q_j(E_j)\in\{0,1\}\]",
        ),
        (
            r"\texttt{U\_j = 1[Q\_j(E\_j) = 1 and T\_j = 0]}.",
            r"\[U_j = 1[Q_j(E_j)=1 \land T_j=0].\]",
        ),
        (
            r"\texttt{C\_j = 1[Q\_j(E\_j) = 0 and T\_j = 1]}.",
            r"\[C_j = 1[Q_j(E_j)=0 \land T_j=1].\]",
        ),
    ]
    count = 0
    for old, new in replacements:
        if old not in tex:
            raise SystemExit(f"ERROR: expected common-framework math token missing: {old}")
        tex = tex.replace(old, new, 1)
        count += 1
    return tex, count


def make_short_tex(md: str) -> str:
    abstract_md, index_md, body_md, ack_md, refs_md = base.parse_manuscript(md)
    abstract_latex = base.pandoc_fragment(abstract_md)
    index_latex = base.pandoc_fragment(index_md)
    body_latex = build_short_body_latex(body_md)
    ack_latex = base.pandoc_fragment(ack_md)
    refs_latex = base.build_references(refs_md)

    tex = rf"""\documentclass[10pt,journal]{{IEEEtran}}
\usepackage{{graphicx}}
\usepackage{{array}}
\usepackage{{url}}
\setlength{{\textwidth}}{{7.10in}}
\setlength{{\columnsep}}{{0.20in}}
\setlength{{\oddsidemargin}}{{-0.30in}}
\setlength{{\evensidemargin}}{{-0.30in}}
\setlength{{\textheight}}{{9.00in}}
\setlength{{\topmargin}}{{0in}}
\setlength{{\headheight}}{{0in}}
\setlength{{\headsep}}{{0in}}
\setlength{{\footskip}}{{0.45in}}
\providecommand{{\tightlist}}{{\setlength{{\itemsep}}{{0pt}}\setlength{{\parskip}}{{0pt}}}}
\setlength{{\emergencystretch}}{{0pt}}

\title{{{base.latex_escape_plain(base.TITLE)}}}
\author{{{base.latex_escape_plain(base.AUTHOR)}\\\small {base.latex_escape_plain(base.AFFILIATION)}}}

\begin{{document}}
\typeout{{TAES_TEXTWIDTH_PT=\the\textwidth}}
\typeout{{TAES_COLUMNSEP_PT=\the\columnsep}}
\typeout{{TAES_COLUMNWIDTH_PT=\the\columnwidth}}
\typeout{{TAES_TEXTHEIGHT_PT=\the\textheight}}
\maketitle

\begin{{abstract}}
{abstract_latex}
\end{{abstract}}

\begin{{IEEEkeywords}}
{index_latex}
\end{{IEEEkeywords}}

{body_latex}

\section*{{Acknowledgment}}
{ack_latex}

{refs_latex}

\end{{document}}
"""
    tex, math_count = convert_common_math(tex)
    if math_count != 3:
        raise SystemExit(f"ERROR: expected three display-math conversions; observed {math_count}")
    if r"\sloppy" in tex:
        raise SystemExit("ERROR: short builder contains \\sloppy")
    return tex


def write_short_audit(result: dict[str, str | int | float | bool]) -> None:
    if result["pages"] <= 8:
        page_decision = "BELOW_TARGET_REVIEW_RESTORE_USEFUL_DETAIL"
    elif result["pages"] == 9:
        page_decision = "PREFERRED_BUFFER_TARGET"
    elif result["pages"] == 10:
        page_decision = "ACCEPTABLE_NO_PRODUCTION_BUFFER"
    else:
        page_decision = "ABOVE_10_ADDITIONAL_COMPRESSION_REQUIRED"

    lines = [
        "TAES_10P_IEEETRAN_BUILD_AUDIT",
        f"short_manuscript_sha256={EXPECTED_SHORT_MD}",
        f"tex_sha256={result['tex_sha256']}",
        f"pdf_sha256={result['pdf_sha256']}",
        f"log_sha256={result['log_sha256']}",
        f"pages={result['pages']}",
        f"estimated_pages_over_10={result['estimated_pages_over_10']}",
        f"page_target_decision={page_decision}",
        f"page_size={result['page_size']}",
        f"textwidth_pt={result['textwidth_pt']:.3f}",
        f"columnsep_pt={result['columnsep_pt']:.3f}",
        f"columnwidth_pt={result['columnwidth_pt']:.3f}",
        f"textheight_pt={result['textheight_pt']:.3f}",
        f"overfull_hbox_count={result['overfull_hbox_count']}",
        f"overfull_vbox_count={result['overfull_vbox_count']}",
        f"underfull_hbox_count={result['underfull_hbox_count']}",
        f"underfull_vbox_count={result['underfull_vbox_count']}",
        f"latex_warning_count={result['latex_warning_count']}",
        f"font_count={result['font_count']}",
        f"font_embedding_all_yes={'PASS' if result['font_embedding_all_yes'] else 'FAIL'}",
        "common_framework_display_math_conversions=3",
        "tables_rendered=I,II,III",
        "figure1_main_article=ABSENT_BY_SHORT_TRACK_DESIGN",
        "supplementary_material_required_for_submission=YES",
        "science_files_changed=NONE",
        "publisher_facing=NO",
        "pdf_visual_qa_required=YES",
    ]
    OUT_AUDIT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    verify_short_binding()

    # Rebind only this process to isolated short-track inputs/outputs.
    base.MANUSCRIPT = SHORT_MD
    base.OUT_TEX = OUT_TEX
    base.OUT_PDF = OUT_PDF
    base.OUT_LOG = OUT_LOG
    base.OUT_AUDIT = OUT_AUDIT
    base.EXPECTED_MANUSCRIPT = EXPECTED_SHORT_MD
    base.TABLE_CAPTIONS = TABLE_CAPTIONS
    base.TABLE_SPECS = TABLE_SPECS
    base.TABLE_HEADER_KEYS = TABLE_HEADER_KEYS
    base.verify_bindings = verify_short_binding
    base.make_tex = make_short_tex

    result = base.build_and_audit()
    write_short_audit(result)

    if result["pages"] <= 8:
        page_decision = "BELOW_TARGET_REVIEW_RESTORE_USEFUL_DETAIL"
    elif result["pages"] == 9:
        page_decision = "PREFERRED_BUFFER_TARGET"
    elif result["pages"] == 10:
        page_decision = "ACCEPTABLE_NO_PRODUCTION_BUFFER"
    else:
        page_decision = "ABOVE_10_ADDITIONAL_COMPRESSION_REQUIRED"

    print("TAES_10P_IEEETRAN_BUILD=PASS_COMPILED_DEVELOPMENT_ONLY")
    print("TAES_10P_IEEETRAN_BUILD_REVISION=1")
    print(f"short_manuscript_sha256={EXPECTED_SHORT_MD}")
    print(f"pages={result['pages']}")
    print(f"estimated_pages_over_10={result['estimated_pages_over_10']}")
    print(f"page_target_decision={page_decision}")
    print(f"page_size={result['page_size']}")
    print("geometry_check=PASS")
    print(f"textwidth_in={result['textwidth_pt'] / 72.27:.3f}")
    print(f"columnsep_in={result['columnsep_pt'] / 72.27:.3f}")
    print(f"columnwidth_in={result['columnwidth_pt'] / 72.27:.3f}")
    print(f"textheight_in={result['textheight_pt'] / 72.27:.3f}")
    print(f"overfull_hbox_count={result['overfull_hbox_count']}")
    print(f"overfull_vbox_count={result['overfull_vbox_count']}")
    print(f"underfull_hbox_count={result['underfull_hbox_count']}")
    print(f"underfull_vbox_count={result['underfull_vbox_count']}")
    print(f"latex_warning_count={result['latex_warning_count']}")
    print(f"font_count={result['font_count']}")
    print(f"font_embedding_all_yes={'PASS' if result['font_embedding_all_yes'] else 'FAIL'}")
    print("common_framework_display_math_conversions=3")
    print("tables_rendered=I,II,III")
    print("figure1_main_article=ABSENT_BY_SHORT_TRACK_DESIGN")
    print(f"tex={OUT_TEX}")
    print(f"tex_sha256={result['tex_sha256']}")
    print(f"pdf={OUT_PDF}")
    print(f"pdf_sha256={result['pdf_sha256']}")
    print(f"log={OUT_LOG}")
    print(f"audit={OUT_AUDIT}")
    print("science_files_changed=NONE")
    print("publisher_facing=NO")
    print("pdf_visual_qa_required=YES")


if __name__ == "__main__":
    main()
