#!/usr/bin/env python3
"""Build the balanced R3 short-form TAES Paper-2 candidate in isolated IEEEtran outputs.

This builder is bound to the exact untracked balanced R3 manuscript generated by
TAES_CREATE_10PAGE_CANDIDATE_R3.py. It reuses the already validated three-table
short-paper renderer and R2 Pandoc math-token handling, but writes only R3-specific
development artifacts.

It does not modify the frozen 16-page R9 package, the canonical R9 manuscript,
the supplementary material, or any Study 3/4/6 science file.
"""

from __future__ import annotations

from pathlib import Path

import TAES_BUILD_10P_IEEETRAN_R1 as r1
import TAES_BUILD_10P_IEEETRAN_R2 as r2

ROOT = Path(__file__).resolve().parent
SHORT_MD = ROOT / "TAES_10P_R3_MANUSCRIPT_DRAFT.md"
OUT_TEX = ROOT / "TAES_10P_R3_MANUSCRIPT_IEEETRAN_DEV.tex"
OUT_PDF = ROOT / "TAES_10P_R3_MANUSCRIPT_IEEETRAN_DEV.pdf"
OUT_LOG = ROOT / "TAES_10P_R3_MANUSCRIPT_IEEETRAN_DEV.log"
OUT_AUDIT = ROOT / "TAES_10P_R3_IEEETRAN_BUILD_AUDIT.txt"

EXPECTED_SHORT_MD = "7fa44eb55255bc7532a01728ab039b5e98fb3c719058f62440310e430b5f7909"
EXPECTED_FROZEN_R9_PDF = "a7624fa416ebe4ba4d0b9e46da25b5dcb4d85e23e63291f4bdf497d5ba6cb319"
FROZEN_R9_PDF = ROOT / "TAES_MANUSCRIPT.pdf"


def verify_r3_binding() -> None:
    if not SHORT_MD.is_file():
        raise SystemExit(
            "ERROR: balanced R3 manuscript missing. Run TAES_CREATE_10PAGE_CANDIDATE_R3.py first."
        )
    actual = r1.base.sha256(SHORT_MD)
    if actual != EXPECTED_SHORT_MD:
        raise SystemExit(
            "ERROR: balanced R3 manuscript hash mismatch: "
            f"expected={EXPECTED_SHORT_MD} actual={actual}"
        )
    if not FROZEN_R9_PDF.is_file():
        raise SystemExit("ERROR: frozen R9 fallback PDF missing")
    frozen = r1.base.sha256(FROZEN_R9_PDF)
    if frozen != EXPECTED_FROZEN_R9_PDF:
        raise SystemExit(
            "ERROR: frozen R9 fallback PDF hash mismatch: "
            f"expected={EXPECTED_FROZEN_R9_PDF} actual={frozen}"
        )


def page_decision(pages: int) -> str:
    if pages <= 7:
        return "BELOW_BALANCED_TARGET_REVIEW_BEFORE_FREEZE"
    if pages in (8, 9):
        return "PREFERRED_BUFFER_TARGET"
    if pages == 10:
        return "ACCEPTABLE_NO_PRODUCTION_BUFFER"
    return "ABOVE_10_ADDITIONAL_EVIDENCE_SAFE_COMPRESSION_REQUIRED"


def write_audit(result: dict[str, str | int | float | bool]) -> None:
    pages = int(result["pages"])
    lines = [
        "TAES_10P_R3_IEEETRAN_BUILD_AUDIT",
        f"balanced_r3_manuscript_sha256={EXPECTED_SHORT_MD}",
        f"frozen_r9_fallback_pdf_sha256={EXPECTED_FROZEN_R9_PDF}",
        "balanced_r3_words_including_references=5625",
        f"tex_sha256={result['tex_sha256']}",
        f"pdf_sha256={result['pdf_sha256']}",
        f"log_sha256={result['log_sha256']}",
        f"pages={pages}",
        f"estimated_pages_over_10={result['estimated_pages_over_10']}",
        f"page_target_decision={page_decision(pages)}",
        f"page_size={result['page_size']}",
        f"textwidth_pt={result['textwidth_pt']:.3f}",
        f"columnsep_pt={result['columnsep_pt']:.3f}",
        f"columnwidth_pt={result['columnwidth_pt']:.3f}",
        f"textheight_pt={result['textheight_pt']:.3f}",
        f"overfull_hbox_count={result['overfull_hbox_count']}",
        f"overfull_vbox_count={result['overfull_vbox_count']}",
        f"underfull_hbox_count={result['underfull_hbox_count']}",
        f"underfull_vbox_count={result['underfull_vbox_count']}",
        f"latex_warning_count={result['latex_warning_count']}",
        f"font_count={result['font_count']}",
        f"font_embedding_all_yes={'PASS' if result['font_embedding_all_yes'] else 'FAIL'}",
        "common_framework_display_math_conversions=3",
        "tables_rendered=I,II,III",
        "figure1_main_article=ABSENT_BY_SHORT_TRACK_DESIGN",
        "supplementary_material_required_for_submission=YES",
        "supplement_content_changed_from_r1=NO",
        "science_files_changed=NONE",
        "study_rerun=NO",
        "publisher_facing=NO",
        "pdf_visual_qa_required=YES",
        "merge_to_main=NOT_AUTHORIZED_UNTIL_QA_PASS",
    ]
    OUT_AUDIT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    verify_r3_binding()

    # Rebind the validated short-paper renderer to the balanced R3 source and
    # isolated R3 output names. The only math-token logic used is the R2 fix.
    r1.SHORT_MD = SHORT_MD
    r1.OUT_TEX = OUT_TEX
    r1.OUT_PDF = OUT_PDF
    r1.OUT_LOG = OUT_LOG
    r1.OUT_AUDIT = OUT_AUDIT
    r1.EXPECTED_SHORT_MD = EXPECTED_SHORT_MD
    r1.convert_common_math = r2.convert_common_math_r2
    r1.verify_short_binding = verify_r3_binding

    r1.base.MANUSCRIPT = SHORT_MD
    r1.base.OUT_TEX = OUT_TEX
    r1.base.OUT_PDF = OUT_PDF
    r1.base.OUT_LOG = OUT_LOG
    r1.base.OUT_AUDIT = OUT_AUDIT
    r1.base.EXPECTED_MANUSCRIPT = EXPECTED_SHORT_MD
    r1.base.TABLE_CAPTIONS = r1.TABLE_CAPTIONS
    r1.base.TABLE_SPECS = r1.TABLE_SPECS
    r1.base.TABLE_HEADER_KEYS = r1.TABLE_HEADER_KEYS
    r1.base.verify_bindings = verify_r3_binding
    r1.base.make_tex = r1.make_short_tex

    result = r1.base.build_and_audit()
    write_audit(result)
    pages = int(result["pages"])

    print("TAES_10P_R3_IEEETRAN_BUILD=PASS_COMPILED_DEVELOPMENT_ONLY")
    print("TAES_10P_R3_IEEETRAN_BUILD_REVISION=1")
    print("r3_source=BALANCED_REVIEWER_USEFUL_RESTORATION")
    print(f"balanced_r3_manuscript_sha256={EXPECTED_SHORT_MD}")
    print("balanced_r3_words_including_references=5625")
    print(f"pages={pages}")
    print(f"estimated_pages_over_10={result['estimated_pages_over_10']}")
    print(f"page_target_decision={page_decision(pages)}")
    print(f"page_size={result['page_size']}")
    print("geometry_check=PASS")
    print(f"textwidth_in={result['textwidth_pt'] / 72.27:.3f}")
    print(f"columnsep_in={result['columnsep_pt'] / 72.27:.3f}")
    print(f"columnwidth_in={result['columnwidth_pt'] / 72.27:.3f}")
    print(f"textheight_in={result['textheight_pt'] / 72.27:.3f}")
    print(f"overfull_hbox_count={result['overfull_hbox_count']}")
    print(f"overfull_vbox_count={result['overfull_vbox_count']}")
    print(f"underfull_hbox_count={result['underfull_hbox_count']}")
    print(f"underfull_vbox_count={result['underfull_vbox_count']}")
    print(f"latex_warning_count={result['latex_warning_count']}")
    print(f"font_count={result['font_count']}")
    print(f"font_embedding_all_yes={'PASS' if result['font_embedding_all_yes'] else 'FAIL'}")
    print("common_framework_display_math_conversions=3")
    print("tables_rendered=I,II,III")
    print("figure1_main_article=ABSENT_BY_SHORT_TRACK_DESIGN")
    print(f"tex={OUT_TEX}")
    print(f"tex_sha256={result['tex_sha256']}")
    print(f"pdf={OUT_PDF}")
    print(f"pdf_sha256={result['pdf_sha256']}")
    print(f"log={OUT_LOG}")
    print(f"audit={OUT_AUDIT}")
    print("frozen_r9_fallback_hash=PASS")
    print("science_files_changed=NONE")
    print("study_rerun=NO")
    print("publisher_facing=NO")
    print("pdf_visual_qa_required=YES")


if __name__ == "__main__":
    main()
