"""JAIS-specific editorial compression profile for Paper 1.

These section overrides are venue-facing editorial condensations derived from the
authoritative target-neutral component manuscript. They do not alter frozen
Study-1/Study-2 populations, statistical results, provenance identities, or
claim boundaries. Numerical Results remain generated from the authoritative
result component files rather than rewritten here.
"""

INTRODUCTION = r'''# 1. Introduction

Spacecraft cybersecurity is a mission-assurance problem as well as an information-security problem. A response that blocks unauthorized activity can also reduce mission service or command availability, and nominal restoration does not establish that software, configuration, authorization, or recovery evidence is trustworthy. Intermittent ground contact makes those trade-offs more consequential because response and recovery can depend on when authorization and evidence are available [@chunawala2026satelliteir; @nist800160v2r1].

Prior work provides the necessary foundations without resolving the post-detection comparison studied here. Mission Aware cybersecurity links unacceptable mission losses to system functions and cyberattack evidence [@bakirtzis2026missionaware]; spacecraft fault detection, isolation, recovery, and trusted-autonomy research addresses safing and restoration under state and communication constraints [@wanninger2025fdir; @thangavel2024trusted; @sarri2026juice]; and cyber-resilience engineering emphasizes anticipation, resistance, recovery, and adaptation [@nist800160v2r1]. Satellite cybersecurity testbeds, datasets, intrusion-detection studies, and risk analyses provide repeatable environments and upstream detection/exposure evidence [@geletko2019nos3; @idan2025aegissat; @chan2026hades; @cucdid_2026; @driouch2024cansatids; @casaril2024satcom; @casaril2026attack_surface]. The narrower question here begins after a cyber-relevant condition is established: how do alternative response and recovery policies behave when mission service, contact, authorization, and evidence quality are explicit constraints?

The article reports two separately frozen software-in-the-loop studies. Study 1 contains 720 VALID observations across 24 cells and evaluates mission state, one modeled missed-contact condition, controlled evidence omission/reduction, trusted recovery, and condition-specific multi-objective policy trade-offs. Study 2 contains a separate 3,872-observation population across 85 cells with zero INVALID attempts. It prospectively expands the evidence model to omission, stale/replayed evidence, contradiction, post-signature manipulation, and bounded producer compromise; adds multiple contact regimes, adversary-budget stress, and context ablations; and compares interpretable deterministic policy families. The populations are never pooled.

Recovery is treated as evidence-qualified rather than merely operational. Study 2 further separates policy-visible evidence qualification from research-only adjudication truth, permitting the experiment to test whether authentic/current-looking evidence can support recovery while still being false when its producer is compromised. The adjudication oracle is never selector input.

The contribution is deliberately bounded: a reproducible satellite-specific method for comparing post-detection response and trusted recovery under explicit contact, authorization, mission, and evidence assumptions; a controlled demonstration that evidence authenticity/currentness is not equivalent to objective correctness under bounded producer compromise; and a pair of integrity-frozen empirical records retaining null, adverse, and conditional outcomes. No weighted global policy score or universal policy rank is used.

Experiments used researcher-controlled NOS3/Fortytwo and core Flight System components [@nasa_nos3; @nasa_cfs]. They did not access operational spacecraft or ground stations, transmit or interfere with radio-frequency systems, use operational credentials, measure real operator or link latency, or establish flight readiness or certification. Study-2 time values are deterministic logical software time. The remainder of the paper reviews the closest prior work, defines the two frozen designs, reports their results separately, and synthesizes their implications and limitations.'''

BACKGROUND = r'''# 2. Background and Related Work

Mission Aware cybersecurity is the principal systems-theoretic framing: mission requirements and unacceptable losses are traced through functions, architecture, dependencies, and cyber consequences [@bakirtzis2026missionaware]. Cyber-resilience guidance complements that framing by separating the ability to withstand, recover from, and adapt to adverse conditions [@nist800160v2r1], while current incident-response guidance treats response and recovery as part of broader risk management [@nist80061r3]. These frameworks motivate the separate containment, mission, command-availability, recovery, and evidence outcomes used here; they are not claimed as new theory or as standards compliance. The Study-1 mission-state proposition is retained despite a null primary result because theoretical relevance does not imply that every implementation will exhibit a measurable state interaction.

Spacecraft fault detection, isolation, and recovery and autonomy research establishes the engineering relevance of safing, restoration, and operation without immediate ground intervention [@thangavel2024trusted; @wanninger2025fdir; @sarri2026juice]. Current satellite incident-response guidance likewise recognizes that containment and recovery can depend on contact opportunities and approval gates [@chunawala2026satelliteir]. The present experiments therefore model contact as a controlled factor, not as orbital geometry, antenna availability, radio propagation, or operator latency.

Trusted recovery is stricter than return to nominal operation. Space-security guidance includes cyber-safe and known-state recovery concepts [@sparta_cybersafe], and broader cyber-physical literature studies recovery controllers and self-healing systems [@lu2024attackrecovery]. Here, recovery requires the frozen evidence appropriate to each study. Study 2 adds the distinction between evidence that satisfies the policy-visible qualification rules and hidden research truth, allowing producer trust to be evaluated separately from signature or freshness checks.

Satellite cyber testbeds and datasets show that simulation, attack generation, and telemetry collection are established capabilities [@geletko2019nos3; @idan2025aegissat; @chan2026hades; @cucdid_2026; @esa_anomaly_2024; @opssat_ad_2025]. Detection-focused research and space-sector exposure analyses address important upstream questions [@driouch2024cansatids; @casaril2024satcom; @casaril2026attack_surface; @dambrosio2025scass; @le2026tinyml; @mattar2025spacecyber]. Temporal-risk work also confirms that mission or time context is active prior art rather than a novelty claim [@liu2026temporal]. The present research object is different: the consequences of alternative response/recovery choices after a modeled cyber-relevant state has already been established.

The frozen event families are related to SPARTA only as behavioral correspondences: unauthorized valid commanding, replayed commands, compromised synthetic updates, and telemetry/evidence degradation map to documented spacecraft-security behaviors without claiming reproduction of complete operational attack chains [@sparta_malicious_valid_gs; @sparta_replay_command_packets; @sparta_onorbit_update; @sparta_compromise_boot_memory; @sparta_telemetry_downlink_modes]. The experiments do not model real ground-station compromise, supply-chain compromise, key theft, or radio-frequency attack mechanisms.

The resulting gap is narrow. Prior work establishes mission-aware analysis, autonomy, fault recovery, cyber resilience, testbeds, detection, and risk assessment. The evidence reported here instead compares multiple post-detection policies while varying modeled contact and evidence conditions, keeping security and mission outcomes separate, and retaining conditions in which the context-sensitive policy is equivalent to or worse than simpler alternatives.'''

METHODS = r'''# 3. Methods

## 3.1 Study 1 design and research boundary

Study 1 used controlled software-in-the-loop experimentation in a NOS3/Fortytwo and core Flight System environment on researcher-controlled infrastructure. A trial combined a frozen cyber event, mission state, evidence condition, contact condition, requested response policy, recovery behavior, and campaign seed. The estimand-driven design contained 24 frozen cells with 30 seeds per cell, yielding 720 VALID observations. Nine INVALID attempts were retained as provenance and retried only for the same seed/cell; they were excluded from statistical membership.

The event families represented an unauthorized but syntactically valid laboratory command (E1), replay of a previously authorized laboratory command (E2), a compromised synthetic software/update context (E3), and reduction/suppression of selected policy-visible evidence fields (E4). Mission states covered nominal, low-power/eclipse, and software-update/recovery contexts as required by the proposition blocks. C0 represented immediate modeled contact and C1 one synthetic missed-contact window. T0 was the full-evidence condition; T1 reduced selected policy-visible evidence. T1 was not a stale, contradictory, forged, or producer-compromise treatment.

The adversary model began from these frozen post-access states. Initial exploitation, credential theft, radio-frequency interception, key extraction, supply-chain compromise, data exfiltration, and physical counterspace attack were outside scope. Immutable treatment identity, seeds, validity rules, experiment ground truth, and provenance controls remained outside the simulated adversary boundary. Runtime policies could use only the context exposed through the frozen policy interface and could not access post-run truth or recovery adjudication as an oracle.

Seven response mechanisms appeared in the final matrix: observation only (P0), identity/source isolation (P1), selective command restriction (P2), a modeled safe-mode transition (P4), verified rollback (P5), wait for ground authorization (P6), and the deterministic mission-aware selector (P7). P7 was a frozen rule-based mechanism, not a learned model. Under P6, immediate or delayed synthetic authorization controlled when the policy could proceed; after authorization, recovery delegated to the P5 rollback mechanism without relabeling the requested/effective P6 policy. `ENTER_SAFE_MODE` was an experimental software action, not validation of a native spacecraft safe mode.

Trusted recovery required all applicable frozen criteria, including approved software/configuration identity, integrity and authorization evidence, current measured-state evidence, restored authorized command capability, ground/spacecraft state agreement, required telemetry and health checks, absence of modeled residual unauthorized state, and a complete recovery record. Primary metrics included unauthorized-effect completion (M01), mission-objective completion (M02), safety-invariant violations (M03), containment time (M04), verified trusted-recovery time (M05), legitimate-command rejection (M06), state-divergence duration (M07), and evidence completeness (M08). The P5 Pareto analysis used only M01, M02, M03, M05, and M06.

For M04/M05, the frozen Study-1 horizon was 30 s and unobserved events were right-censored rather than imputed. The locked population contained 180 observed M05 recovery events and 540 censored observations. Every cell contained exactly 30 VALID repetitions and all 30 campaign seeds were represented.

## 3.2 Study 1 statistical analysis and reproducibility

Analysis used exactly the 720 frozen VALID observations, with campaign seed as the blocking/resampling unit. P1 evaluated mission-state dependence on the predeclared M01, M02, M03, and M06 outcomes. P2 compared P6 and P7 across C0/C1 using 30-s restricted mean survival time for M04/M05 and a paired duration contrast for M07, with seed-block bootstrap intervals. P3 compared trusted recovery under T0/T1. P4 traced actual effective policy/action and consequences from execution metadata rather than inferring selection from expected policy or hidden truth. P5 used condition-specific Pareto comparison across nine frozen groups; lower M01/M03/M05/M06 and higher M02 were preferred. Twenty thousand paired seed-bootstrap replicates provided marginal 95% intervals. No p-values, weighted primary score, or global policy ranking were computed for P5.

The authoritative ledger contains 729 records: 720 VALID and nine INVALID attempts. Ten VALID observations were executed on two earlier orchestration/finalization commits, while 710 used the final execution baseline. A predeclared analytical-exchangeability review found no scientific-core change, and a 29-seed/696-observation complete-block sensitivity restricted to the final execution commit preserved every P7 Pareto-front classification, pairwise relation, and primary-metric direction. The sensitivity did not replace the 720-observation population.

Study-1 raw evidence and integrity material are archived on Zenodo. Because the original executable WP10 statistical-analysis source was not preserved, a later public reconstruction starts from frozen derived inputs and regression-validates against preserved authoritative outputs without rerunning the experiment or redefining the historical population.

## 3.3 Study 2 design

Study 2 (`S2-AEATR-001`) was prospectively specified as a separate study and did not append observations to Study 1. Its frozen matrix contained 85 cells and 3,872 planned positions, all of which were retained as VALID with zero INVALID attempts. Block A used 18 cells × 96 paired seeds (1,728 observations) as the primary evidence-mechanism block; Blocks B–E used 32 paired seeds per cell for estimation/sensitivity. The 96-seed primary design was selected prospectively from a worst-case Wilson 95% half-width target of no more than 0.10.

Evidence conditions were complete/current (V0), omitted (V1), stale/replayed (V2), contradictory independent evidence (V3), post-signature manipulation (V4), and bounded partial producer compromise (V5). Adversary budgets ranged from A0 through A3. A1 permitted one policy-visible producer to be controlled; A2 combined one controlled producer with modeled contact unavailability and is therefore a coupled producer-compromise/contact-loss profile rather than an adversary-only treatment; A3 permitted at least two policy-visible producers while the verifier and independent trust anchor remained outside the adversary budget.

The deterministic policy set comprised fail-closed (`S2_B0_FAIL_CLOSED`), fail-operational (`S2_B1_FAIL_OPERATIONAL`), risk-threshold (`S2_B2_RISK_THRESHOLD`), and evidence-aware (`S2_S1_EVIDENCE_AWARE`) mechanisms, plus prespecified context/security ablations. K0–K3 formed the ordered contact-outage series; K4 was a separate intermittent/flapping-contact condition. Frozen logical timing used a 10-s decision point, 8-s current-evidence issue time, 5-s evidence-validity interval, 5-s recovery-processing increment, and a 240-s right-censor horizon. K0 was continuously available; K1, K2, and K3 became available at 20, 60, and 180 s; K4 used intermittent windows. These are deterministic software-model times, not measured spacecraft, orbital, network, operator, or radio-frequency latencies.

Block A crossed six evidence/adversary profiles with three policies under a frozen update/recovery context. Block B crossed K0–K4 with four policies to evaluate contact/authorization. Block C applied BENIGN/ADVERSARIAL labels within matched ambiguity families but did not change hidden truth or generated policy-visible evidence; it is therefore a structural label-invariance control rather than a causal discrimination experiment. Block D compared the full evidence-aware selector with mission-, evidence-, contact-, and security-context ablations. Block E stressed A1/K0, A2/K2, and A3/K0 profiles across three policies.

Study 2 strictly separated policy-visible evidence from research-only adjudication truth. The selector could not access treatment identity, ground truth, provenance controls, or the correctness oracle. This permits a compromised producer to generate a cryptographically valid/current-looking claim that satisfies policy-visible qualification while remaining false relative to hidden truth; evidence-qualified recovery is therefore not defined as objective correctness.

Primary outcomes were unsafe-permissive response rate, false-conservative response rate, evidence-qualified trusted recovery, time to evidence-qualified recovery, residual unauthorized state, and legitimate-command rejection. Secondary outcomes included containment time, state divergence, selection stability, and terminal state. Recovery/containment time used the frozen 240-logical-second restricted horizon.

## 3.4 Study 2 analysis and assurance

Primary Block-A contrasts were paired by frozen seed and reported with 95% confidence intervals without a primary p-value gate. Secondary paired contrasts, K0–K3 trends, and policy-by-contact interactions were grouped into seven prespecified families with Holm adjustment within family and endpoint. K4 remained separate from the ordered trend; A2/K2 remained contact-coupled; and 32-seed secondary blocks were interpreted as estimation/sensitivity evidence rather than powered small-effect confirmatory tests. No weighted global policy score or rank was computed.

The Phase-6 evidence artifact and Phase-7 analysis implementation were cryptographically frozen before aggregate analysis. Phase 7 generated 85 cell summaries, 162 primary contrast rows, 432 secondary contrast rows, and 85 terminal-state summaries. An independent standard-library implementation recomputed every numerical cell summary, primary contrast, secondary contrast, Holm adjustment/rejection flag, and terminal-state distribution with zero mismatches.

Before campaign execution, implementation-bound security testing and bounded TLA+ model checking evaluated selected oracle-isolation, evidence-qualification, trust-boundary, and recovery invariants. These checks provide pre-runtime design/implementation assurance only; they are not proofs of complete implementation equivalence, operational correctness, cryptographic security, flightworthiness, or certification.'''

DISCUSSION = r'''# 5. Discussion

The two frozen studies expose a consistent systems-security result without supporting universal policy superiority: response value depends on the mechanism, contact/authorization regime, and the sufficiency and trustworthiness of the evidence visible to that mechanism. Study 1 supplies the baseline multi-objective comparison; Study 2 raises the evidence-integrity and contact-assurance bar in a separate population.

## 5.1 Mission state, contact, and authorization

Mission-aware and spacecraft fault-management theory make state-dependent consequences plausible [@bakirtzis2026missionaware; @wanninger2025fdir; @thangavel2024trusted; @sarri2026juice], but Study 1 did not demonstrate mission-state dependence on its predeclared M01, M02, M03, and M06 outcomes. That null result is retained rather than replaced with an exploratory endpoint.

Contact/authorization produced clearer effects. In Study 1, one synthetic missed-contact window added about 10 s to P6 containment, verified-recovery, and state-divergence timing, while P7 was approximately unchanged. In Study 2, the evidence-aware selector restricted first and waited for the next frozen contact opportunity, retaining unsafe-permissive rate 0 under K1–K4. The fail-closed baseline eventually recovered but its initial permissive action under unavailable authorization produced unsafe-permissive behavior. These results do not make autonomous response universally preferable: they show that the action taken while authority is unavailable must be explicit. K4 remains intermittent/flapping contact, and all reported times are logical software times rather than operational latency.

## 5.2 Evidence sufficiency and evidence-plane trust

Study 1 showed that omission/reduction of selected policy-visible fields can redirect a deterministic selector and prevent trusted recovery. Fixed P5 recovered in all tested repetitions under both Study-1 evidence conditions, whereas P7 moved from 30/30 trusted recoveries under T0 to 0/30 under T1 in the compromised-update block. T1 supports only an omission/reduction claim; it did not test stale evidence, contradiction, post-signature manipulation, or producer compromise.

Study 2 separated those mechanisms prospectively. V1–V4 caused restrictive/hold behavior for fail-closed and evidence-aware policies under the Block-A prerequisites. V5 exposed the stronger boundary: a compromised producer could make a false claim that remained authentic/current enough to satisfy the recovery gate. Under V5, fail-closed and evidence-aware policies both achieved evidence-qualified recovery in all 96 paired primary observations while adjudicated unsafe-permissive rate remained 1.0.

This finding is not an argument that signature verification failed. Authentication can establish origin and post-signature integrity without establishing that the signer is uncompromised or the signed claim is true. Trusted-recovery assurance must therefore state which evidence producers are inside the trust boundary and adversary budget. The research-only adjudication truth was never policy input, preserving the question the experiment was designed to test.

## 5.3 Context-dependent trade-offs and structural controls

Study-1 Pareto analysis produced benefit, equivalence, mixed performance, and disadvantage. Study 2 reached a compatible conclusion through endpoint-specific contrasts rather than reusing the Pareto framework. Under V5, evidence-aware permissiveness could support evidence-qualified recovery while simultaneously carrying an unsafe-permissive difference. Context ablations also showed scenario-specific dependencies: removing mission or contact context increased unsafe-permissive behavior in the unauthorized-command context, while a security-only update/recovery ablation prevented qualified recovery and added restricted recovery time. Labels such as mission aware, fail closed, risk threshold, or evidence aware therefore describe mechanisms, not guarantees.

Block C provides a useful negative control but not causal discrimination evidence. Its BENIGN/ADVERSARIAL label does not alter hidden truth or generated policy-visible evidence within each ambiguity family, so the 54 zero contrasts demonstrate structural label invariance only. A genuine fault-versus-attack ambiguity experiment would need distinct hidden causal mechanisms with deliberately matched or overlapping observables.

## 5.4 Relation to prior work and design implications

Testbeds, telemetry datasets, trusted autonomy, fault recovery, detection, attack-surface analysis, and cyber-safe recovery are established areas [@geletko2019nos3; @idan2025aegissat; @cucdid_2026; @chan2026hades; @thangavel2024trusted; @wanninger2025fdir; @driouch2024cansatids; @casaril2024satcom; @casaril2026attack_surface; @lu2024attackrecovery]. The contribution here is not ownership of those concepts but a reproducible post-detection comparison that makes authorization, contact, mission cost, evidence sufficiency, producer trust, and recovery qualification measurable together.

For system design, five questions follow directly: which actions require remote authorization; what action is taken while authorization is absent; which evidence is required before recovery; which evidence producers must remain trustworthy; and what mission/command cost is accepted for containment or fallback. These questions align with response/recovery concerns in cyber-resilience and incident-response guidance [@nist800160v2r1; @nist80061r3] without constituting standards compliance.

## 5.5 Limitations and future validation

Both studies are controlled software-in-the-loop experiments. They do not reproduce full spacecraft dynamics, flight-processor constraints, radio propagation, operational ground networks, orbital-access schedules, or human procedures. Study-1 C1 and Study-2 K0–K4 are synthetic contact constructs; their times must not be interpreted as operational latency. The event/adversary coverage is bounded and does not establish behavior for untested attack chains or mission architectures.

Study-1 T1 models omission/reduction only; Study 2 uses deterministic synthetic evidence and producer keys and does not test real key theft, supply-chain compromise, hardware roots of trust, or production attestation infrastructure. The bounded formal models strengthen assurance for encoded abstractions but do not verify the complete implementation or operational spacecraft. The response policies are deterministic rules, not learned agents. No Study-1 M03 safety-invariant violations were observed, which is not proof of universal safety. Study-2 Blocks B–E use 32 paired seeds as estimation/sensitivity evidence, so absence of small effects must not be interpreted as equivalence without appropriate design support.

Neither study includes human participants or operational validation, and neither establishes flightworthiness, certification, or safe production autonomy. Study 1 and Study 2 should remain frozen. Future work should use separate protocols for genuine causal benign-versus-adversarial ambiguity, higher-fidelity orbital/access and radio-frequency-free hardware-in-the-loop validation, human authorization research under appropriate approvals, and evidence-plane assurance under producer/key compromise and independent corroboration.'''

CONCLUSION = r'''# 6. Conclusion

Two separately frozen software-in-the-loop studies evaluated satellite cyber response and trusted recovery without pooling their populations or constructing a global policy score. Study 1 did not demonstrate mission-state dependence on predeclared primary outcomes, but modeled missed contact delayed the ground-authorized path and reduced policy-visible evidence changed deterministic response and recovery behavior. Its Pareto comparisons were condition-specific rather than uniformly favorable.

Study 2 established a stronger evidence-trust boundary. Under bounded producer compromise, fail-closed and evidence-aware policies could satisfy the evidence-qualified recovery gate in all 96 paired primary observations while research-only adjudication still classified unsafe-permissive rate as 1.0. Under modeled non-immediate contact, the evidence-aware selector retained unsafe-permissive rate 0 by restricting until the next frozen contact opportunity, whereas the fail-closed baseline became initially unsafe-permissive. Context ablations showed specific dependencies, and Block C remains a structural label-invariance control rather than evidence of causal fault-versus-attack discrimination.

The combined evidence supports explicit evaluation of authorization, contact, evidence sufficiency, evidence-producer trust, recovery qualification, and mission/command costs. It does not establish operational flight readiness, radio-frequency performance, operator latency, certification, or a universally preferred autonomous policy. The central assurance question is therefore not whether a spacecraft can respond autonomously, but whether the implemented response can contain the modeled threat, preserve prioritized service and command authority, and return to a state supported by evidence that is sufficient and trustworthy under the stated adversary model.'''
